name: 'Explorer Integration Reporter'
description: 'Reports integrations back into main for DORA metrics'
author: 'Global'
inputs:
  github-token: # change this
    required: true
    description: 'A github token with repo access'
runs:
  using: 'node16'
  main: 'dist/index.js'
